parameters:
#    leha_echantillon.example.class: Leha\EchantillonBundle\Example

services:
#    leha_echantillon.example:
#        class: %leha_echantillon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
