<?php

namespace Leha\HistoriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributRequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributRequeteRepository extends EntityRepository
{
	public function getByRequeteType(Requete $requete, $type)
	{
        $attributs_requete = $this->getEntityManager()->createQuery('select ar from LehaHistoriqueBundle:AttributRequete ar where ar.requete_id = :requete_id and ar.type = :type order by ar.ordre')
            ->setParameter('requete_id', $requete->getId())
            ->setParameter('type', $type)
            ->getResult();
		
		return $attributs_requete;
	}
}
