<?php

namespace Leha\HistoriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributRequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributRequeteRepository extends EntityRepository
{
	/*public function getByAttributRequete(Critere $critere, Requete $requete)
	{
		$query = $this->getEntityManager()->createQuery('select cr from LehaHistoriqueBundle:CritereRequete cr');
		
		$dd = $query->getSingleResult();
		exit;

		return $dd; 
	}*/
}
