<?php

namespace Leha\HistoriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CritereRequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritereRequeteRepository extends EntityRepository
{
	public function getByCritereRequete(Critere $critere, Requete $requete)
	{
		
		$query = $this->getEntityManager()->createQuery('select cr from LehaHistoriqueBundle:CritereRequete cr');
		
		$dd = $query->getSingleResult();
		exit;
		//$query->setParameter('critere_id', $critere->getId());
		//$query->setParameter('requete_id', $requete->getId());
		
		return $dd; 
	}
}
