<?php

namespace Leha\HistoriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends EntityRepository
{
    public function getRequeteByUser()
    {
        return $this->getEntityManager()
            ->createQuery('select r from LehaHistoriqueBundle:Requete r order by r.libelle asc')
            ->getResult();
    }
}
