parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     central_leha
    database_user:     root
    database_password: leha35

    test_database_driver:   pdo_mysql
    test_database_host:     127.0.0.1
    test_database_port:     ~
    test_database_name:     central_leha_test
    test_database_user:     root
    test_database_password: leha35

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
