leha_attribut:
    resource: "@LehaAttributBundle/Resources/config/routing.yml"
    prefix:   /

leha_echantillon:
    resource: "@LehaEchantillonBundle/Resources/config/routing.yml"
    prefix:   /

leha_dashboard:
    resource: "@LehaDashboardBundle/Resources/config/routing.yml"
    prefix:   /

leha_historique:
    resource: "@LehaHistoriqueBundle/Resources/config/routing.yml"
    prefix:   /

leha_user:
    resource: "@LehaUserBundle/Resources/config/routing.xml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller:LehaUserBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout
