leha_dashboard:
    resource: "@LehaDashboardBundle/Resources/config/routing.yml"
    prefix:   /

leha_historique:
    resource: "@LehaHistoriqueBundle/Resources/config/routing.yml"
    prefix:   /

leha_user:
    resource: "@LehaUserBundle/Resources/config/routing.xml"
    prefix:   /
