security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER,ROLE_LEHA_ADMIN_USERADMIN_LIST,ROLE_LEHA_ADMIN_USERADMIN_EDIT,ROLE_LEHA_ADMIN_USERADMIN_CREATE,ROLE_LEHA_ADMIN_USERADMIN_VIEW]
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main_dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            form_login:
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: false



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }