<?php

namespace Leha\EchantillonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributEchantillonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributEchantillonRepository extends EntityRepository
{
}
