leha_usertest_security_login:
    pattern:  /login
    defaults: { _controller: LehaUserTestBundle:Security:login }

leha_usertest_security_check:
    pattern:  /login_check
    defaults: { _controller: LehaUserTestBundle:Security:check }

leha_usertest_security_logout:
    pattern:  /logout
    defaults: { _controller: LehaUserTestBundle:Security:logout }
leha_usertest_register:
     pattern:  /register
     defaults: { _controller: FOSUserBundle:Registration:register }

leha_usertest_passwd:
     pattern:  /passwd
     defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }