<?php
namespace Leha\CentralBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SearchAttributesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //foreach ($options['attribut_requete'] as $attribut) {
            /**
             * @var $attribut \Leha\CentralBundle\Entity\Attribut
             */
            //$attribut = $attributRequete->getAttribut();

          //  $builder->add($attribut->getFieldId(), $attribut->getType(), $attribut->getFieldOptions());
        //}

        $builder->add('value', null, array(
            'label' => 'ok'
        ));
    }


    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'leha_historique_search_attributes';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

        /*$resolver
            ->setRequired(array(
                'attribut_requete'
            ));
        */
        $resolver
            ->setDefaults(array(
                'data_class' => 'Leha\CentralBundle\Entity\AttributEchantillon'
            ));
    }
}