parameters:
    leha_requete.handler.class: Leha\CentralBundle\Form\Handler\RequeteHandler
    leha_requete.manager.class: Leha\CentralBundle\Services\RequeteManager

services:
    leha_requete.manager:
        class: %leha_requete.manager.class%
        arguments: [@doctrine.orm.default_entity_manager]
    leha_requete.handler:
        class: %leha_requete.handler.class%
        arguments: [@leha_requete.manager, @security.context]