leha_user_security_login:
    pattern:  /login
    defaults: { _controller: LehaUserBundle:Security:login }

leha_user_security_check:
    pattern:  /login_check
    defaults: { _controller: LehaUserBundle:Security:check }

leha_user_security_logout:
    pattern:  /logout
    defaults: { _controller: LehaUserBundle:Security:logout }
leha_user_register:
     pattern:  /register
     defaults: { _controller: FOSUserBundle:Registration:register }

leha_user_passwd:
     pattern:  /passwd
     defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }