leha_historique:
    pattern:  /historique
    defaults: { _controller: LehaHistoriqueBundle:Default:index}

leha_historique_add:
    pattern:  /historique/add
    defaults: {_controller: LehaHistoriqueBundle:Default:add}

leha_historique_edit:
    pattern:  /historique/edit/{id}
    defaults: {_controller: LehaHistoriqueBundle:Default:edit}

leha_historique_search:
    pattern:  /historique/recherche/{id}
    defaults: {_controller: LehaHistoriqueBundle:Default:search}

leha_historique_remove:
    pattern: /historique/remove/{id}
    defaults: {_controller: LehaHistoriqueBundle:Default:remove}

leha_historique_choix_attributs:
    pattern: /historique/choix_attributs/{id}
    defaults: {_controller: LehaHistoriqueBundle:Default:choix_attributs}