services:
    leha.admin.useradmin:
        class: Leha\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "User" }
        arguments:
            - ~
            - Leha\UserTestBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [YourNSAdminBundle]]