services:
    leha.admin.useradmin:
        class: Leha\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "User" }
        arguments:
            - ~
            - Leha\UserBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setUserManager, [@fos_user.user_manager]]
    leha.admin.groupadmin:
        class: Leha\AdminBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "Group" }
        arguments:
            - ~
            - Leha\UserBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            -  [ setGroupManager, [@fos_user.group_manager]]

