<?php

namespace Leha\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EchantillonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchantillonRepository extends EntityRepository
{
    public function getAll()
    {
        $query = $this->joinAttributs($this->createQueryBuilder('e'))
            ->getQuery();

        return $query->getResult();
    }

    public function getQueryBuilderFiltered($values)
    {
        $queryBuilder = $this->createQueryBuilder('e')->select('e');

        foreach ($values as $property => $value) {
            $queryBuilder->andWhere('e.' . $property . ' = :' . $property)
                ->setParameter(':' . $property, $value);
        }

        /*$filter = implode(' AND ', $filter);
        if (strlen($filter) > 0) {
            $queryBuilder->where($filter);
            foreach ($values as $key => $value) {
                $queryBuilder->setParameter(':'.$key, $value);
            }
        }*/

        $this->joinAttributs($queryBuilder);

        return $queryBuilder;
    }

    /**
     * @param \Doctrine\ORM\QueryBuilder $qb
     * @param string $alias
     * @return mixed
     */
    private function joinAttributs($qb, $alias = 'e')
    {
        $qb->leftJoin($alias . '.echantillonAttributs', 'ea')
            ->leftJoin('ea.attribut', 'eaa')
            ->addSelect('eaa, ea');

        return $qb;
    }
}
