<?php

namespace Leha\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Leha\CentralBundle\Entity\AttributRequete;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends EntityRepository
{

}
