<?php

namespace Leha\AnalyseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyseRepository extends EntityRepository
{
    public function getListeAnalyseDisponible(Requete $requete)
    {
        /*$this->getEntityManager()
            ->createQuery("select a from LehaAnalyseBundle a where requete")*/

    }
}
