<?php

namespace Leha\AttributBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Leha\HistoriqueBundle\Entity\AttributRequete;

/**
 * AttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributRepository extends EntityRepository
{

}
