parameters:
#    leha_client.example.class: Leha\ClientBundle\Example

services:
#    leha_client.example:
#        class: %leha_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
