parameters:
#    leha_attribut.example.class: Leha\AttributBundle\Example

services:
#    leha_attribut.example:
#        class: %leha_attribut.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
