parameters:
    leha_attribut.manager.class: Leha\AttributBundle\Services\AttributManager

services:
    leha_attribut.manager:
        class: %leha_attribut.manager.class%
        arguments: [@doctrine.orm.default_entity_manager]

#    leha_attribut.example:
#        class: %leha_attribut.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
